### PR TITLE
Add query params to GTM script url

### LINKED ISSUE #72: queryParams is not working
Hi,

I implement my website with different Environment like staging and rc.
I found there is a property call queryParams that I can place gtm_auth, gtm_preview, gtm_cookies_win.

But when I published Google Tag Manager and I check browser with chrome plugin called "Tag Assistant". I saw there is no queryParams append to url.

The Screenshot below is "Tag Assistant" result that implemented with vue-gtm. It is not working.

The Screenshot below is "Tag Assistant" result that implemented with copied <script> code from google tag, and it works.

I already fill in gtm_auth, gtm_preview, gtm_cookies_win in the queryParams just like the official sample code of vue-gtm github page.

Does anyone encountered the same problem? Thanks.

### PR DESCRIPTION
**Pull request by babysharny**
Fixes #72

### CODE REVIEW

**Comment by pibemillo** [comment]
I am experiencing this same issue. Any idea when this will get merged in and be made available on npm?

**Comment by acudworth** [comment]
can we get this merged asap @mib200? This fixes key functionality, thanks

**Comment by simplenotezy** [comment]
@mib200 - merge please ;)

**Comment by simplenotezy** [comment]
I guess @mib200 could refuse to migrate this, as it has dependency on `URLSearchParams` which is not supported in IE.

**Comment by simplenotezy** [comment]
I tried getting your branch to work on my site, however, I couldn't. I ran yarn build (to get the dist file reflect your changes), but got:

```
ERROR in ./src/index.js
Module parse failed: /Users/constantsolutions/Projects/jwr-nuxt/node_modules/vue-gtm/src/index.js Unexpected token (13:15)
You may need an appropriate loader to handle this file type.
| const install = function (Vue, initConf = {}) {
|   // Apply default configuration
|   initConf = { ...pluginConfig, ...initConf }
|
|   pluginConfig.id = initConf.id
 @ multi ./src/index.js
```

**Comment by mib200** [comment]
Merged

**Comment by mib200** [comment]
merged

**Pull request merged**
