### PR TITLE
Make GTM ID a config option

### LINKED ISSUE #24: Cookies being set when enabled set to false
_GA cookies are still being set, when enabled is set to false:

```javascript
// Init Google GTM
Vue.use(VueGtm, {
    enabled: false, // until we have a cookie allowed
    debug: false, // @todo we need config.json for this
    vueRouter: router,
});
```

Is this supposed to happen?

### LINKED ISSUE #25: [Request] Dynamically inject script to allow preprod and prod GTM IDs
Right now it's only possible to use a single GTM ID since it's hardcoded in the `index.html` file. If you were to load the script dynamically like [how react-google-tag-manager](https://github.com/holidaycheck/react-google-tag-manager/blob/master/src/build_parts.js) does it, then you could allow dynamically setting the GTM ID, so that it's possible to use different IDs in preprod vs prod environments.

I think this API would be ideal:

```js
Vue.use(VueGtm, {
  id: 'GTM-XXXX'   // insert ID here, which you can change programatically per environment
  enabled: true,
  debug: true,
  vueRouter: router
});
```

### PR DESCRIPTION
**Pull request by rokkie**
Fixes #24 
Fixes #25

### CODE REVIEW

**Comment by mib200** [comment]
@rokkie can you also provide a documentation on how we are planning to use these changes, that closes #25 ?

**Comment by rokkie** [comment]
I've updated the readme.
It fixes #24 by not injecting the GTM script tag when `enabled` is `false`.
It fixed #25 by allowing an additional `id` option.

**Comment by evan-coygo** [comment]
@mib200 can you cut a release now that this has been merged?

**Comment by mib200** [comment]
@evan-coygo release as version 2 on NPM. 👍

**Pull request merged**
